### ISSUE TITLE
Атомарность требования 3.1.4 History

### ISSUE THREAD

**Issue by Igor-Kholupko** [MaryBurshtyn/FeedMe#1]
Для требования [3.1.4 History (Show History)](https://github.com/MaryBurshtyn/FeedMe/blob/master/Documentation/SRS.md#314-history) имеется возможность разбиения на ряд более детальных (в качестве примера одного из более детальных можно привести требование из пункта [3.1.3 Feeding (Show last food)](https://github.com/MaryBurshtyn/FeedMe/blob/master/Documentation/SRS.md#313-feeding)).  
  
P. S. После пункта [3.1.4 History](https://github.com/MaryBurshtyn/FeedMe/blob/master/Documentation/SRS.md#314-history) следующий пункт повторяет нумерацию [3.1.4 Analysis](https://github.com/MaryBurshtyn/FeedMe/blob/master/Documentation/SRS.md#314-analysis).

**Comment by MaryBurshtyn** [comment]
Спасибо, будет исправлено!
