### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by NasterVill** [MaryBurshtyn/FeedMe#2]
Your code is written well, and the general structure of your project is understandable and not complicated. To my mind, only few changes, that relate to code style, are to be introduced. Here is the list of them:

in FeedActivity.java
	row 14 : Unused import 'import android.util.Log;'
	row 207 : 'if' statement can be simplified to "return netInfo != null && netInfo.isConnected(); "
in HistoryActivity.java 
	row 11: Unused import 'import java.text.DateFormat;'
	row 79: 'for' loop replaceable with 'foreach' like "for (HistoryNote aDay : day) {"
in Settings.java 
	row 5 : Unused import 'import java.util.ArrayList;'
in History.java 
	row 71 : String values are compared using '==', not 'equals()'
in startActivity.java 
	row 17: mistake "firtRun" instead of "firstRun"

**Comment by MaryBurshtyn** [comment]
Thank you . All issues solved.
